export const fileTypes = {
  forge: 'Ubisoft Anvil',
  pak: 'Unreal Engine Pak',
  sig: 'Signature',
  dll: 'Windows Executable',
  exe: 'Windows Executable',
  msi: 'Windows Installer',
  appx: 'Windows Appx',
  bat: 'Windows Batch',
  cmd: 'Windows Batch',
  reg: 'Windows Registry',
  ps1: 'Windows PowerShell',
  vbs: 'Windows VBScript',
  wsf: 'Windows Script',
  wsh: 'Windows Script',
  js: 'JavaScript',
  json: 'JSON',
  html: 'HTML',
  htm: 'HTML',
  css: 'CSS',
  txt: 'Text',
  ini: 'INI',
  conf: 'INI',
  log: 'Log',
  md: 'Markdown',
  markdown: 'Markdown',
  yml: 'YAML',
  yaml: 'YAML',
  xml: 'XML',
  svg: 'SVG',
  ttf: 'TrueType Font',
  woff: 'Web Open Font Format',
  woff2: 'Web Open Font Format',
  eot: 'Embedded Open Type',
  otf: 'Open Type Font',
  png: 'PNG',
  jpg: 'JPEG',
  jpeg: 'JPEG',
  gif: 'GIF',
  bmp: 'BMP',
  ico: 'ICO',
  tiff: 'TIFF',
  tif: 'TIFF',
  webp: 'WebP',
  pdf: 'PDF',
  mp3: 'MP3',
  mp4: 'MP4',
  aac: 'AAC',
  m4a: 'AAC',
  oga: 'OGG',
  ogg: 'OGG',
  wav: 'WAV',
  webm: 'WebM',
  flac: 'FLAC',
  mkv: 'Matroska',
  avi: 'AVI',
  wmv: 'WMV',
  mov: 'QuickTime',
  qt: 'QuickTime',
  '3gp': '3GP',
  flv: 'FLV',
  swf: 'SWF',
  doc: 'Word',
  docx: 'Word',
  resS: 'Unity Resource',
};
